export const ADD_NEW_LIST = 'ADD_NEW_LIST'
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const EDIT_TASK_NAME = 'EDIT_TASK_NAME'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_LIST = 'DELETE_LIST'
export const CHANGE_TITLE = 'CHANGE_TITLE'